input_video: /checkpoint/repligen/fkokkinos/outputs/034_EVAL_mvdream_emu_16f_vpred_top100k_uniform_emuvideoeval/A_product_photo_of_a_toy_tank.mp4
input_video_frames: 16
prompt: 'A product photo of a toy tank, rich details, static, high resolution, 4k,
  8k, canon 5d mark iii, studio lighting, bright, intricate details, highly realistic '
negative_prompt: ugly, bad anatomy, bad geometry, low quality, blurry, black, silhouette,
  inconsistent
elevation: -3.2485
ref_size: 512
density_thresh: 0.1
input_video_frames_skip: null
ablation_frames_skip: 1
outdir: /checkpoint/repligen/fkokkinos/gs_JAN31_emu100k_dt800_cfgsweep/u2net/TCF_0_ICFG_5_EMU_100k_A_product_photo_of_a_toy_tank/
mesh_format: obj
batch_size: 16
iters: 1500
iters_refine: 50
radius: 1.0
fovy: 49.1
load: null
train_geo: false
invert_bg_prob: 0.0
vis_interval: 400
jitter_elevation: true
mask_model: u2net
depth_model: vitl
lambda_rgb: 0.0
lambda_mask: 1.0
lambda_depth: 0.0
lambda_lpips: 10.0
lambda_ssim: 0.2
start_lpips: 100
lambda_laplacian: 1.0
lambda_normals: 1.0
lambda_opacity: 0.0001
lambda_opaque: 0.5
lambda_scales: 0.0001
lambda_sparsity: 0.0
lambda_position: 1.0
emuvideo_path: experiments/fkokkinos/034_EVAL_mvdream_t2i2v_emu_16f_vpred_top100k_uniform_mast.yaml
denoise_timestep: 800
denoise_start: 500
denoise_every: 500
guidance_scale: 0
guidance_scale_image: 5
num_pts: 5000
sh_degree: 0
position_lr_init: 0.001
position_lr_final: 2.0e-05
position_lr_delay_mult: 0.02
position_lr_max_steps: 500
feature_lr: 0.01
opacity_lr: 0.05
scaling_lr: 0.005
rotation_lr: 0.005
percent_dense: 0.1
density_start_iter: 100
density_end_iter: 1000000
densification_interval: 50
opacity_reset_interval: 1000000
densify_grad_threshold: 0.01
gui: false
force_cuda_rast: true
dmtet_grid: 128
mesh_scale: 2.1
geom_lr: 0.0001
texture_lr: 0.2
mask: u2net
